export enum SortBy {
  ASCENDING = 'ASCENDING',
  DESCENDING = 'DESCENDING',
  MOST_LIKED = 'MOST_LIKED',
  MOST_COMMENTED = 'MOST_COMMENTED',
  RECENTLY_CREATED = 'RECENTLY_CREATED',
  RECENTLY_UPDATED = 'RECENTLY_UPDATED',
}
